name: movie_stack
description: "A movies database app to explore and manage movie details."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  retrofit: ^4.7.2
  json_annotation: ^4.8.1
  hive: ^2.2.3
  get_it: ^8.2.0
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.2
  google_fonts: ^6.3.0
  carousel_slider: ^5.1.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  fpdart: ^1.1.1
  go_router: ^16.2.0
  logger: ^2.6.1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  readmore: ^3.0.0
  stream_transform: ^2.1.1
  url_launcher: ^6.3.2
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # Dev-only packages moved here
  build_runner: ^2.4.6
  retrofit_generator: ^8.2.1
  json_serializable: ^6.7.0
  hive_generator: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env